[package]
name = "sim-replay"
edition.workspace = true
version.workspace = true

[dependencies]
sim-core = { path = "../sim-core" }
sim-data = { path = "../sim-data" }
serde = { workspace = true }
thiserror = { workspace = true }
ron = { workspace = true }
blake3 = { workspace = true }

[lints]
workspace = true
